name: Compile App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar o JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          
      - name: Gerar o Gradle Wrapper
        shell: pwsh
        run: gradle wrapper
      
      - name: Dar permissão e rodar o Gradle para gerar o executável
        shell: pwsh
        run: |
          gradlew createLaunch4j

      - name: Salvar o .exe como artefato
        uses: actions/upload-artifact@v4
        with:
          name: meu-executavel
          path: build/launch4j/*.exe
